= Build a Kubernetes Cluster on Raspberry Pi
:hp-tags: Kubernetes, RaspberryPi
:numbered:

== Required hardware

To build this 4 Pi setup I used 

* 4 Raspberry Pi 2 with a quad core CPU and 1 GB of RAM
* 4 16 GB MicroSD cards - class 10
* 1 60 W power supply with USB outlets
* 4 short USB to Micro USB cables for powering the Pi's
* 4 short cat 5 network cables
* 1 longer cat 5 network cable to hook into your network
* 1 network hub (mine is an old 5 port 10/100 Mbs I dusted off)
* Lego's from your childhood. Just get creative. Trust me it feels good to build your own!

It is important to get class 10 MicroSD cards as this is the one component that affects the speed of the system greatly. You can easily get away with a smaller 20W powersupply for 4 Pi's, I'm planning on adding more Pi's later so I got a bigger one.) The network port on the Pi is 100 Mbs, so you can use your old hub.


<image>

== Flashing the MicroSD cards

The first thing we need to do now is to get the operating system onto the MicroSD Cards. I'm using an Hypriot image. I did test a bunch of different images [1] including Pidora, Redsleeve/Centos7, ArchLinux, but concluded that Hypriot is the best for me at this point. Mostly because of the native Docker support and the image being small. You can download the latest hypriot image from [2].  The following instructions are OSX specific. 

1. Insert the memory card in the card reader.
2. Unmount the card (using the du utility)
3. sudo dd bs=1m if=hypriot-rpi-20151103-224349.img of=/dev/disk2
4. wait .. this may take 10 minutes or so.

Do this for all 4 MicroSD cards. You can work on your lego casing while waiting.

== Power up and add DNS

You can now power up the first Pi. By default to login use root/hypriot. You will need to set up DNS for each of the Pi's. If you don't want to hook up a monitor and keyboard to login at the console to figure out its IP and Mac address, then you can use nmap [3] to figure this out. If you have a DNS service provision it there, or else name the Pi's in /etc/hosts. I named my Pi's _rpi-master_, _rpi-node-1_, _rpi-node-2_ and _rpi-node-3_. With a quick reboot of each Pi you will see the names reflected at the cmd prompt. Note that if you skip the DNS step your Kubernetes cluster will not work. 

== Add Swap (optional)

I added 1Gb of swap space to my _rpi-master_ because it runs a few more Kubernetes components. Some people seem concerned that frequent writes to the MicroSD card will make it fail quickly. I therefore decided to set the 'swappiness' such that it only uses the swap as a last resort.
....
    dd if=/dev/zero of=/swap/swapfile bs=1M count=1024
    mkswap /swap/swapfile
    swapon /swap/swapfile
....
Now you can check with 'top' that you have a 1 GB of swapspace
....
KiB Mem:    947468 total,   913096 used,    34372 free,    69884 buffers
KiB Swap:  1048572 total,      484 used,  1048088 free,   667248 cached
....
To make the swap permanent between reboots add
....
/swap/swapfile none swap sw 0 0
....
to you _/etc/fstab_ file. Finally in the _/etc/sysctl.conf_ I've set the swappiness to 1 to make it not very 'swappy'
....
vm.swappiness = 1
....
'1' means it will only use swap when the RAM use gets over 99%.

== Intall Kubernetes

These instructions are to install the plain vanilla Kubernetes from Google. I had some issues compiling Openshift v3 due to some 64 bit dependencies, and I will get back to that later. I would like go support both. All the code that I'm using is checked in under https://github.com/Project31.

=== Golang on Pi (optional)

If you have a Linux or OSX machine you can simply compile the Kubernetes Go libraries for ARM on that, but if you want to can install Golang one the Pi too. For that run
....
    apt-get update 
    apt-get upgrade
    apt-get install gcc apt-get install make
    git clone https://go.googlesource.com/go
    cd go git fetch --all
    git checkout go1.4.3
    cd src ./all.bash
....
    
=== Compile Kubernetes for ARM (optional)

To compile Kubernetes for arm you need to checkout the Kubernetes from git and update he client and service compile targets which I have already done for you if you checkout https://github.com/Project31/kubernetes/. The compilation requires a Docker daemon, so on OSX use boot2docker, for example
....
boot2docker start
....
with output:
....
Waiting for VM and Docker daemon to start...
.............oooo
Started.
Writing /Users/kstam/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/kstam/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/kstam/.boot2docker/certs/boot2docker-vm/key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH=/Users/kstam/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1
....

Set the required system parameters and now to compile the binaries simply run
....
    git clone git@github.com:Project31/kubernetes.git
    cd kubernetes/build
    ./run.sh hack/build-cross.sh
....

This will output
....
+++ [1204 10:50:30] Verifying Prerequisites....
+++ [1204 10:50:31] Building Docker image kube-build:cross.
+++ [1204 10:50:34] Building Docker image kube-build:build-f8d233d305.
+++ [1204 10:50:39] Running build command....
+++ [1204 15:50:41] Multiple platforms requested, but available 2G < threshold 11G, building platforms in serial
+++ [1204 15:50:41] Building go targets for linux/arm:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubemark
    cmd/hyperkube
    cmd/linkcheck
    plugin/cmd/kube-scheduler
+++ [1204 15:51:11] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubemark
    cmd/hyperkube
    cmd/linkcheck
    plugin/cmd/kube-scheduler
+++ [1204 15:51:40] Multiple platforms requested, but available 2G < threshold 11G, building platforms in serial
+++ [1204 15:51:40] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    cmd/genswaggertypedocs
    examples/k8petstore/web-server/src
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [1204 15:51:52] Building go targets for linux/386:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    cmd/genswaggertypedocs
    examples/k8petstore/web-server/src
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [1204 15:52:01] Building go targets for linux/arm:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    cmd/genswaggertypedocs
    examples/k8petstore/web-server/src
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [1204 15:52:10] Building go targets for darwin/amd64:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    cmd/genswaggertypedocs
    examples/k8petstore/web-server/src
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [1204 15:52:20] Building go targets for darwin/386:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    cmd/genswaggertypedocs
    examples/k8petstore/web-server/src
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [1204 15:52:29] Building go targets for windows/amd64:
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    cmd/genswaggertypedocs
    examples/k8petstore/web-server/src
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [1204 15:52:39] Placing binaries
+++ [1204 10:52:56] Running build command....
+++ [1204 10:52:58] Output directory is local.  No need to copy results out.
....
and the binaries for arm can be found in __output/dockerized/bin/linux/arm_. 
....
-rwxr-xr-x  1 kstam  admin  36378096 Dec  4 10:52 e2e.test
-rwxr-xr-x  1 kstam  admin  28074776 Nov 12 14:26 genbashcomp
-rwxr-xr-x  1 kstam  admin  23070656 Nov 12 14:25 genconversion
-rwxr-xr-x  1 kstam  admin  23064640 Nov 12 14:25 gendeepcopy
-rwxr-xr-x  1 kstam  admin  28075952 Nov 12 14:26 gendocs
-rwxr-xr-x  1 kstam  admin  49536096 Nov 12 14:25 genkubedocs
-rwxr-xr-x  1 kstam  admin  28088896 Nov 12 14:26 genman
-rwxr-xr-x  1 kstam  admin  11703416 Nov 12 14:25 genswaggertypedocs
-rwxr-xr-x  1 kstam  admin   7626288 Dec  4 10:52 ginkgo
-rwxr-xr-x  1 kstam  admin  49826704 Nov 12 14:20 hyperkube
-rwxr-xr-x  1 kstam  admin  50032864 Nov 12 14:26 integration
-rwxr-xr-x  1 kstam  admin  41280520 Dec  4 10:51 kube-apiserver
-rwxr-xr-x  1 kstam  admin  35882152 Dec  4 10:51 kube-controller-manager
-rwxr-xr-x  1 kstam  admin  25615024 Nov 12 14:20 kube-proxy
-rwxr-xr-x  1 kstam  admin  24984232 Dec  4 10:51 kube-scheduler
-rwxr-xr-x  1 kstam  admin  28069864 Nov 12 14:26 kubectl
-rwxr-xr-x  1 kstam  admin  40450728 Nov 12 14:20 kubelet
-rwxr-xr-x  1 kstam  admin  39144744 Nov 12 14:20 kubemark
-rwxr-xr-x  1 kstam  admin   2764048 Nov 12 14:20 linkcheck
-rwxr-xr-x  1 kstam  admin   2933872 Nov 12 14:25 mungedocs
-rwxr-xr-x  1 kstam  admin   5572640 Nov 12 14:25 src
....
These binaries are simply uploaded to: https://github.com/Project31/kubernetes-arm from where they will be downloaded during the _master_ and _node_ installation.


=== Install Kubernetes on the Master


== References

1. http://kurtstam.blogspot.com/2015/03/pi-oneering-on-raspberry-pi-2-part-1.html
2. http://blog.hypriot.com/downloads/
3. https://kurtstam.github.io/2015/07/14/Turn-your-Raspberry-Pi-2-into-a-Hotspot.html
4. http://kubernetes.io/v1.1/docs/design/architecture.html


