= Getting started with Fabric8 and OpenShift v3 on OSX
:hp-tags: OpenShift, Fabric8, OSX
:numbered:

The full fabric8 docs can be found http://fabric8.io/v2/openShiftDocker.html[here]. Here I took the relavant sections applicable to running on OSX, and I added some notes. OpenShift v3 relies on Docker for its container management. OSX does not support Docker natively. The http://fabric8.io/v2/openShiftDocker.html[recommended way] is to use vagrant to create a VM with the correct Docker configuration.

== Prerequisites

Install whatever the newest version is of the following:

* Docker Client - Just following the https://docs.docker.com/installation/mac/[instructions for Docker on OSX], but know we will not be using Boot2Docker.
* Vagrant - Download the OSX version from http://www.vagrantup.com/downloads.html[Vagrant] and install.
* VirtualBox - Download the OSX version from https://www.virtualbox.org/wiki/Downloads[VirtualBox] and install.


== Creating the fabric8 Virtual Machine

To create the VM on Virtual Box we simply use the https://github.com/fabric8io/fabric8/blob/master/Vagrantfile[Vagrantfile] in the root of the https://github.com/fabric8io/fabric8[fabric8] root directory. Either download the https://github.com/HubPress/hubpress.io/archive/master.zip[zip] of use git to get a clone of the repository
....
git clone https://github.com/fabric8io/fabric8.git
....

WARNING: The Vagrantfile is configured to build a VM with https://github.com/fabric8io/fabric8/blob/master/Vagrantfile#L32[4 VPUs  and 8192MB of Ram]. It is recommended to not exceed about half of your machine's resources. In my case that meant having to set this to 2 VPUs and 4096MB of Ram.

NOTE: Hopefully we can reduce the resource usage!

Now that we have updates the Vagrantfile with resonable settings for your machine we can create it using
....
vagrant up
....
This can take a bit depending on your network speed. Currently it builds Ubuntu-trusty-64 image, but hopefully it will build a Centos-7 image soon. You can ty other images from https://github.com/fabric8io/fabric8/tree/master/support/vagrant[here].

== Deploying fabric8 onto the Virtual Machine

....
vagrant@vagrant-ubuntu-trusty-64:~$ bash <(curl -sSL https://bit.ly/get-fabric8)
Validating your environment...

Validating firewall rules

Configuring OpenShift authentication
time="2015-04-06T18:20:33Z" level="fatal" msg="Error response from daemon: Conflict. The name \"openshift\" is already in use by container 2057970e35cc. You have to delete (or rename) that container to be able to reuse that name." 
Waiting for Kubernetes master
router
router
docker-registry
docker-registry
Manage authorization policy

Available Commands: 
  add-role-to-user       add users to a role
  remove-role-from-user  remove user from role
  remove-user            remove user from project
  add-role-to-group      add groups to a role
  remove-role-from-group remove group from role
  remove-group           remove group from project
  who-can                who-can <verb> <resource>

Use "openshift ex --help" for a list of all commands available in openshift ex.
Use "openshift ex <command> --help" for more information about a given command.
Use "openshift ex options" for a list of global command-line options (applies to all commands).
services/fabric8-console-service
replicationControllers/fabric8-console-controller
services/app-library
replicationControllers/app-library-controller
services/app-library-jolokia
services/fabric8-forge
replicationControllers/fabric8-forge-controller

Waiting for services to fully come up - shouldn't be too long for you to wait

Waiting for Fabric8 console
Configuring OpenShift oauth
oAuthClients/fabric8-console

Waiting for Docker registry

You're all up & running! Here are the available services:

Service              | URL                                                         
-------              | ---                                                         
Kubernetes master    | https://127.0.0.1:8443                                      
Fabric8 console      | http://172.30.17.107/                                       
Docker Registry      | 172.30.17.14:5000                                           

Set these environment variables on your development machine:

export FABRIC8_CONSOLE=http://172.30.17.107/
export DOCKER_REGISTRY=172.30.17.14:5000
export KUBERNETES_TRUST_CERT=true
export DOCKER_IP=172.28.128.4
export DOCKER_HOST=tcp://172.28.128.4:2375
export KUBERNETES_MASTER=https://172.28.128.4:8443
vagrant
....