= Change the Kubernetes Domain on OpenShift
:hp-tags: OpenShift, Fabric8, Kubernetes

The KUBERNETES_DOMAIN is defaulted to _vagrant.f8_ in Fabric8, and if you forgot to set this system parametes before running the fabric8 install then you end up with routes containing the vagrant.f8 domain. To fix this you will have to reinstall the console. First 

....
export KUBERNETES_DOMAIN=<yourdomain>
oc delete route fabric8
oc delete rc fabric8
systemctl stop openshift
docker kill <fabric8-container-id>
docker rm <fabric8-container-id>
docker rmi <fabric8-image-id>
systemctl start openshift
gofabric8 deploy
....

Verify the new domain is updated using
docker inspect <fabric8-container-id> | grep "OAUTH_AUTHORIZE_URI"

Finally there is one more thing to do which is to update where the openshift needs to redirect to after authentication, use

....
oc edit oauthclient fabric8
....

and replace _vagrant.f8_ with your domain.

NOTE: If your new domain name ends in _.f8_ and you have DNS issues this may be from Landrush trying to do the resolving for you. Check your _/etc/resolver_ directory and if it has a _f8_ file, delete it, as you probably want it to resolve the _vagrant.f8_ domain only.

