= Kubernetes API Management importing a Camel with serious Swagger 
:hp-tags: Fabric8, Kubernetes, Apiman

== Introduction

Not too long ago http://www.davsclaus.com/2015/09/apache-camel-216-swagger-java-and-api.html[Claus Ibsen demo'ed] the camel-swagger module. The http://camel.apache.org/swagger-java.html[camel-swagger module] allows you to describe your http://camel.apache.org/[Camel] REST service using Swagger DSL. In this blogpost we converted his example to run on `Kubernetes` using `Fabric8`. After deploying the service to Kubernetes we can then import the API into the API Manager that is http://www.apiman.io/latest/[Apiman]. Once imported the SwaggerJSON DSL is presented to API consumers in a nice viewer.


== Obtaining and deploying the camel-swagger quickstars

It is assumed you have a running Fabric8 instance running on Openshift 3 with Apiman deployed. Check https://kurtstam.github.io/2015/09/29/One-click-to-run-Apiman-on-Fabric8.html[this] post if you don't. Next, fork and clone the ipaas-quickstarts repository

....
git clone https://github.com/fabric8io/ipaas-quickstarts
....

To deploy the quickstart login to your Kubernetes master and invoke the f8-local-deploy profile running maven

....
oc login <your master>
cd ipaas-quickstarts/quickstarts/cdi/camel-swagger
mvn -Pf8-local-deploy
....

== Import the camel-swagger API



